# Generated by Django 5.2.5 on 2026-04-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards_api', '0002_add_board_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='color',
            field=models.CharField(default='#29abe2', max_length=7),
        ),
    ]
