# Generated by Django 5.2.5 on 2026-04-20 08:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards_api', '0003_add_board_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='boardmember',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='boardmember',
            constraint=models.UniqueConstraint(fields=('board', 'user'), name='unique_board_member'),
        ),
    ]
