# Generated by Django 5.2.5 on 2026-04-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards_api', '0005_add_board_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmember',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('editor', 'Editor'), ('viewer', 'Viewer')], default='editor', max_length=10),
        ),
    ]
