# Generated by Django 5.2.5 on 2026-05-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards_api', '0007_add_board_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardfavorite',
            options={'ordering': ['order', 'created_at']},
        ),
        migrations.AddField(
            model_name='boardfavorite',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
