# Generated by Django 5.2.5 on 2026-06-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_api_a_event_t_c2d3a4_idx',
            old_name='audit_api_a_event_t_idx',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='event_type',
            field=models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('password_reset', 'Password Reset'), ('totp_enabled', 'Totp Enabled'), ('totp_disabled', 'Totp Disabled'), ('board_member_added', 'Board Member Added'), ('board_member_removed', 'Board Member Removed'), ('board_member_role_changed', 'Board Member Role Changed'), ('team_member_added', 'Team Member Added'), ('team_member_removed', 'Team Member Removed'), ('team_member_role_changed', 'Team Member Role Changed'), ('account_deleted', 'Account Deleted'), ('admin_action', 'Admin Action'), ('superuser_board_access', 'Superuser Board Access')], max_length=40),
        ),
    ]
