# Generated by Django 5.2.5 on 2026-04-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0005_add_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='totp_secret',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
