# Generated by Django 5.2.5 on 2026-06-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0006_increase_totp_secret_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Platform admin: access to the admin dashboard. Does not grant access to private boards.'),
        ),
    ]
