# Generated by Django 6.0.8 on 2026-09-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0008_alter_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='totp_last_counter',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
