# Generated by Django 5.2.5 on 2026-04-20 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards_api', '0004_alter_boardmember_unique_together_and_more'),
        ('notifications_api', '0002_notification_fk_board_task'),
        ('tasks_api', '0012_alter_label_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='boards_api.board'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='tasks_api.task'),
        ),
    ]
