# Generated by Django 5.2.5 on 2026-04-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_api', '0004_add_notification_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='email_delivery',
            field=models.CharField(choices=[('instant', 'Instant'), ('digest', 'Daily digest'), ('none', 'No emails')], default='instant', max_length=10),
        ),
    ]
