# Generated by Django 5.2.5 on 2026-05-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_api', '0005_add_email_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('assignment', 'Assignment'), ('comment', 'Comment'), ('mention', 'Mention'), ('automation', 'Automation')], max_length=20),
        ),
    ]
