# Generated by Django 6.0.8 on 2026-09-24 11:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards_api', '0009_boardinvitelink'),
        ('notifications_api', '0006_alter_notification_type'),
        ('tasks_api', '0028_remove_task_unique_task_order_per_column'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', '-created_at'], name='notif_recipient_created_idx'),
        ),
    ]
