# Generated by Django 5.2.5 on 2026-04-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('columns_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='wip_limit',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
