# Generated by Django 5.2.5 on 2026-04-20 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_api', '0001_initial'),
        ('tasks_api', '0016_add_time_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityentry',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tasks_api.task'),
        ),
    ]
