# Generated by Django 6.0.8 on 2026-09-24 11:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_api', '0002_add_task_fk'),
        ('boards_api', '0009_boardinvitelink'),
        ('tasks_api', '0028_remove_task_unique_task_order_per_column'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='activityentry',
            index=models.Index(fields=['board', '-created_at'], name='activity_board_created_idx'),
        ),
    ]
