# Generated by Django 5.2.5 on 2026-04-12 16:14

import django.db.models.deletion
import tasks_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_api', '0006_add_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=tasks_api.models.attachment_path)),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tasks_api.task')),
            ],
        ),
    ]
