# Generated by Django 5.2.5 on 2026-04-15 08:27

import tasks_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_api', '0007_add_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(storage=tasks_api.models._private_storage, upload_to=tasks_api.models.attachment_path),
        ),
    ]
