# Generated by Django 5.2.5 on 2026-04-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards_api', '0003_add_board_color'),
        ('columns_api', '0001_initial'),
        ('contacts_api', '0001_initial'),
        ('tasks_api', '0008_alter_attachment_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['order', 'created_at']},
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['board', 'order'], name='tasks_api_t_board_i_58d676_idx'),
        ),
    ]
