# Generated by Django 5.2.5 on 2026-04-20 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards_api', '0004_alter_boardmember_unique_together_and_more'),
        ('tasks_api', '0011_fk_to_m2m_assignees'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='label',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='label',
            constraint=models.UniqueConstraint(fields=('board', 'name'), name='unique_label_per_board'),
        ),
    ]
