# Generated by Django 5.2.5 on 2026-04-20 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards_api', '0006_add_member_role'),
        ('tasks_api', '0014_add_task_dependency'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('select', 'Select')], max_length=10)),
                ('options', models.JSONField(blank=True, default=list)),
                ('order', models.PositiveIntegerField(default=0)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='boards_api.board')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='TaskFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, default='')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='tasks_api.customfield')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='tasks_api.task')),
            ],
        ),
        migrations.AddConstraint(
            model_name='customfield',
            constraint=models.UniqueConstraint(fields=('board', 'name'), name='unique_custom_field_per_board'),
        ),
        migrations.AddConstraint(
            model_name='taskfieldvalue',
            constraint=models.UniqueConstraint(fields=('task', 'field'), name='unique_task_field_value'),
        ),
    ]
