# Generated by Django 5.2.5 on 2026-04-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards_api', '0007_add_board_team'),
        ('columns_api', '0002_column_wip_limit'),
        ('contacts_api', '0003_alter_contact_unique_together_and_more'),
        ('tasks_api', '0017_add_comment_parent'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['board', 'archived_at', 'order'], name='tasks_api_t_board_i_cca9da_idx'),
        ),
    ]
