# Generated by Django 5.2.5 on 2026-05-24 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_api', '0019_add_comment_task_created_index'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='comment',
            new_name='tasks_api_c_task_id_7933c8_idx',
            old_name='tasks_api_co_task_id_created_idx',
        ),
    ]
