# Generated by Django 5.2.5 on 2026-05-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_api', '0020_rename_tasks_api_co_task_id_created_idx_tasks_api_c_task_id_7933c8_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
