# Generated by Django 5.2.5 on 2026-05-25 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards_api', '0007_add_board_team'),
        ('tasks_api', '0021_task_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('priority', models.CharField(blank=True, default='medium', max_length=10)),
                ('subtasks', models.JSONField(blank=True, default=list)),
                ('label_ids', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_templates', to='boards_api.board')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('board', 'name'), name='unique_template_per_board')],
            },
        ),
    ]
