# Generated by Django 5.2.5 on 2026-05-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_api', '0022_tasktemplate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subtask',
            options={'ordering': ['order', 'pk']},
        ),
        migrations.AddField(
            model_name='subtask',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
