# Generated by Django 5.2.5 on 2026-05-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_api', '0025_taskwatcher'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='cover_image_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
