# Generated by Django 5.2.5 on 2026-05-26 11:58

from django.db import migrations, models


def space_out_orders(apps, schema_editor):
    Task = apps.get_model('tasks_api', 'Task')
    column_ids = (
        Task.objects.filter(column__isnull=False, archived_at__isnull=True)
        .values_list('column_id', flat=True)
        .distinct()
    )
    for col_id in column_ids:
        tasks = list(
            Task.objects.filter(column_id=col_id, archived_at__isnull=True)
            .order_by('order', 'created_at')
        )
        for i, task in enumerate(tasks):
            task.order = float(i * 1024)
        Task.objects.bulk_update(tasks, ['order'])


class Migration(migrations.Migration):

    dependencies = [
        ('boards_api', '0009_boardinvitelink'),
        ('columns_api', '0002_column_wip_limit'),
        ('contacts_api', '0003_alter_contact_unique_together_and_more'),
        ('tasks_api', '0026_task_cover_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='order',
            field=models.FloatField(default=0.0),
        ),
        migrations.RunPython(space_out_orders, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True), ('column__isnull', False)), fields=('column', 'order'), name='unique_task_order_per_column'),
        ),
    ]
