# Generated by Django 5.2.5 on 2026-05-29 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_api', '0027_task_order_float_and_unique'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='task',
            name='unique_task_order_per_column',
        ),
    ]
