# Generated by Django 5.2.5 on 2026-05-24 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boards_api', '0007_add_board_team'),
        ('tasks_api', '0020_rename_tasks_api_co_task_id_created_idx_tasks_api_c_task_id_7933c8_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('trigger_type', models.CharField(choices=[('task_moved_to_column', 'Task Moved To Column'), ('task_created', 'Task Created'), ('priority_set', 'Priority Set'), ('all_subtasks_done', 'All Subtasks Done'), ('deadline_approaching', 'Deadline Approaching'), ('label_added', 'Label Added')], max_length=50)),
                ('trigger_config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to='boards_api.board')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.CharField(max_length=50)),
                ('actions_executed', models.JSONField(default=list)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards_api.board')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_logs', to='tasks_api.task')),
                ('rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='automations_api.automationrule')),
            ],
            options={
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='RuleAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('move_to_column', 'Move To Column'), ('set_priority', 'Set Priority'), ('assign_user', 'Assign User'), ('set_label', 'Set Label'), ('remove_label', 'Remove Label'), ('notify_creator', 'Notify Creator'), ('notify_assignees', 'Notify Assignees'), ('notify_user', 'Notify User')], max_length=50)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('order', models.PositiveIntegerField(default=0)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='automations_api.automationrule')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RuleCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_type', models.CharField(choices=[('priority_equals', 'Priority Equals'), ('label_set', 'Label Set'), ('assignee_equals', 'Assignee Equals')], max_length=50)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='automations_api.automationrule')),
            ],
        ),
    ]
